name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, Windows]
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Environment
      shell: powershell
      run: |
        Write-Host "##[group]System Verification"
        docker --version
        minikube version
        kubectl version --client
        Write-Host "##[endgroup]"

    - name: Start Minikube Cluster
      shell: powershell
      run: |
        $minikubeStatus = minikube status -o json | ConvertFrom-Json
        if (-not $minikubeStatus.Host) {
          minikube start --driver=docker --memory=4096
          minikube addons enable ingress
        }
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Docker Images
      shell: powershell
      run: |
        docker build -t hudanyazee/frontend:latest ./frontend
        docker build -t hudanyazee/backend:latest ./backend

    - name: Login to Docker Hub
      shell: powershell
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Images
      shell: powershell
      run: |
        docker push hudanyazee/frontend:latest
        docker push hudanyazee/backend:latest

    - name: Deploy to Kubernetes
      shell: powershell
      run: |
        kubectl create namespace mern-app --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/mongodb/ -n mern-app
        kubectl apply -f k8s/backend/ -n mern-app
        kubectl apply -f k8s/frontend/ -n mern-app
        kubectl rollout restart deployment frontend -n mern-app
        kubectl rollout restart deployment backend -n mern-app
