name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Minikube
      shell: cmd
      run: |
        choco install minikube -y
        minikube start
        minikube addons enable ingress

    - name: Set up Docker for Minikube
      shell: cmd
      run: |
        @FOR /f "tokens=*" %i IN ('minikube -p minikube docker-env --shell cmd') DO @%i

    - name: Build Frontend Image
      run: docker build -t hudanyazee/frontend:latest ./frontend

    - name: Build Backend Image
      run: docker build -t hudanyazee/backend:latest ./backend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Images
      run: |
        docker push hudanyazee/frontend:latest
        docker push hudanyazee/backend:latest

    - name: Create Namespace if not exists
      run: |
        kubectl get namespace mern-app || kubectl create namespace mern-app
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/mongodb/ -n mern-app
        kubectl apply -f k8s/backend/ -n mern-app
        kubectl apply -f k8s/frontend/ -n mern-app
        kubectl rollout restart deployment frontend -n mern-app
        kubectl rollout restart deployment backend -n mern-app