name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure Minikube is running
      shell: powershell
      run: |
        minikube status || minikube start --driver=docker
        minikube addons enable ingress

    - name: Set up Docker for Minikube
      shell: "C:\\Program Files\\PowerShell\\7\\pwsh.exe"  # Using full path to pwsh
      run: |
        minikube docker-env | Invoke-Expression
        docker ps  # Verify connection

    - name: Build and Push Images
      shell: cmd  # Using cmd for better compatibility
      run: |
        docker build -t hudanyazee/frontend:latest ./frontend
        docker build -t hudanyazee/backend:latest ./backend
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push hudanyazee/frontend:latest
        docker push hudanyazee/backend:latest

    - name: Create Namespace if not exists
      shell: cmd
      run: |
        kubectl create namespace mern-app --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Kubernetes
      shell: cmd
      run: |
        kubectl apply -f k8s/mongodb/ -n mern-app
        kubectl apply -f k8s/backend/ -n mern-app
        kubectl apply -f k8s/frontend/ -n mern-app
        kubectl rollout restart deployment frontend -n mern-app
        kubectl rollout restart deployment backend -n mern-app