name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, Windows]  # Explicit labels
    timeout-minutes: 30  # Prevent hanging

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: 'src'  # Explicit checkout path

    - name: Verify Environment
      shell: powershell
      run: |
        Write-Host "##[group]System Verification"
        docker --version
        minikube version
        kubectl version --client
        Write-Host "##[endgroup]"

    - name: Start Minikube Cluster
      shell: powershell
      run: |
        $minikubeStatus = minikube status -o json | ConvertFrom-Json
        if (-not $minikubeStatus.Host) {
          minikube start --driver=docker --memory=4096
          minikube addons enable ingress
        }
        minikube docker-env | Invoke-Expression

    - name: Build Docker Images
      shell: cmd
      run: |
        cd src
        docker build -t hudanyazee/frontend:latest ./frontend
        docker build -t hudanyazee/backend:latest ./backend

    - name: Login to Docker Hub
      shell: bash
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Images
      shell: cmd
      run: |
        docker push hudanyazee/frontend:latest
        docker push hudanyazee/backend:latest

    - name: Deploy to Kubernetes
      shell: powershell
      run: |
        # Create namespace if not exists
        kubectl create namespace mern-app --dry-run=client -o yaml | kubectl apply -f -
        
        # Apply configurations
        kubectl apply -f src/k8s/mongodb/ -n mern-app
        kubectl apply -f src/k8s/backend/ -n mern-app
        kubectl apply -f src/k8s/frontend/ -n mern-app
        
        # Restart deployments
        kubectl rollout restart deployment frontend -n mern-app
        kubectl rollout restart deployment backend -n mern-app